apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
        - name: movie-container
          image: movieapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
